# Site
name: '能无吱'
description: 'Pintereso is a free Jekyll theme for awesome people like you, Pinterest like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
paginate: 10
paginate_path: /page/:num/
all_dir: all/
categories_dir: categories
author_dir: /author
include: ["_pages"]


# Navigation buttons in the front page.s
nav:         
    - {title: 作者, description: 关于作者, url: 'https://nengwuzhi.github.io/authors-list'} 
    - {title: 全部, description: 全部文章, url: 'https://nengwuzhi.github.io/all'}
    - {title: 分享, description: dragula, url: 'https://nengwuzhi.github.io/dragula'}
    - {title: tab, description: tab, url: 'https://nengwuzhi.github.io/tab'}
    - {title: gallery, description: gallery, url: 'https://nengwuzhi.github.io/gallery'}    
authors:
  
  author1:
    name: 能无知
    site: https://nengwuzhi.github.io/
    avatar: assets/images/avatar1.jpg
    bio: "嗨，我是无知，主题的作者，您当前正在预览的主题。 我希望你喜欢它！"
    email: mailto:author1thunaseer@gmail.com
    twitter: https://twitter.com/nengwuzhi
    instagram: https://www.instagram.com/nengwuzhi/
  
  author2:
    name: 能无为
    site: https://nengwuwei.com/
    avatar: assets/images/avatar2.jpg
    bio: "博主，时尚达人，没有作为！"
    email: mailto:author2chemmengath@gmail.com
    twitter: https://twitter.com/nengwuwei
    instagram: https://www.instagram.com/nengwuwei/
# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
